# Generated by Django 4.2.3 on 2025-02-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('sala konferencyjna', 'Sala Konferencyjna'), ('pojazd', 'Pojazd'), ('sprzęt IT', 'Sprzęt IT')], default='sala konferencyjna', max_length=100),
        ),
    ]
